[package]
name = "soundboard"
version = "0.1.0"
edition = "2024"

[dependencies]
elgato-streamdeck = { version = "0.12.0", features = ["async"] }
tokio = { version = "1", features = ["full"] }
pipewire = "0.9.2"
hound = "3.5.1"
image = "0.25.1"
